name = "sydrix"
compatibility_date = "2025-05-01"
account_id = "6c462cd675d7e03eea794481c1202c94"
workers_dev = true

site = { bucket = "./dist" }

main = "worker.js"

[build]
external = ["@cloudflare/kv-asset-handler"]
